name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install libqt5widgets5 libqt5gui5
      - name: configure
        run: 
           cmake -Bbuild
      - name: build
        run: cmake --build build --config $BUILD_TYPE -j4
